### ISSUE TITLE
Possible constructor injection of DomainService into ApplicationService

### ISSUE THREAD

**Issue by sdaves** [MichalPaszkiewicz/cqrs-react-router#12]
Thanks for the great library!

Looks like the domainService instance created in the tests aren't used or tested. How do you feel about having ApplicationService take a DomainService instance as an argument to its constructor?

https://github.com/MichalPaszkiewicz/cqrs-react-router/blob/master/tests/services/applicationservice.ts#L54

**Comment by sdaves** [comment]
https://github.com/MichalPaszkiewicz/cqrs-react-router/issues/12

**Comment by MichalPaszkiewicz** [comment]
Nice work, thanks a lot!

**Comment by sdaves** [comment]
Thanks for the quick merge, what would you say it the process for bumping the package.json version number and publishing to npm?
